[package]
name = "peer"
version = "0.1.0"
edition = "2024"

[dependencies]
logic = {path = "../logic"}
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
crossterm = "0.27"
rand = "0.8"